name: Build
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - image: "ubuntu:noble"
          - image: "ubuntu:plucky"
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          make all image=${{ matrix.image }}
